# Generated by Django 3.2.3 on 2021-11-13 15:51

from django.db import migrations, models
import fileServers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('general_file', models.FileField(upload_to=fileServers.models.GeneralFile.file_upload_location)),
            ],
        ),
    ]
